# Limpieza proyecto 3

#### Primero se trae la data del csv

In [1]:
import pandas as pd

data = pd.read_csv("datos_norte_santander.csv")
data.head()

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20112,TI,SB11201120186494,URBANO,N,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001009017,54,...,No,No,Si,A-,41.00,31.00,NaN,NaN,NaN,NaN
1,20194,TI,SB11201940250932,URBANO,NaN,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001002136,54,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
2,20194,TI,SB11201940250932,URBANO,NaN,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001002136,54,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
3,20112,TI,SB11201120193635,RURAL,N,A,ACADÉMICO,2.540510e+11,254051000821,54,...,No,No,No,A-,34.00,39.00,NaN,NaN,NaN,NaN
4,20102,TI,SB11201020198930,URBANO,N,A,TÉCNICO/ACADÉMICO,1.548740e+11,154874000806,54,...,No,No,No,A-,38.53,50.82,NaN,NaN,NaN,NaN

#### Ahora revisamos los duplicados

In [2]:
duplicates = len(data[data.duplicated()])
print(f'Number of Duplicate Entries: {duplicates}')

Number of Duplicate Entries: 35924

In [3]:
data[data.duplicated()]

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
2,20194,TI,SB11201940250932,URBANO,NaN,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001002136,54,...,No,Si,Si,A-,32.0,45.0,42.0,42.0,49.0,218.0
6,20194,TI,SB11201940475810,URBANO,N,A,ACADÉMICO,1.548740e+11,154874000016,54,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
22,20194,TI,SB11201940484666,URBANO,N,A,TÉCNICO/ACADÉMICO,2.548740e+11,254874000363,54,...,No,No,Si,A1,49.0,52.0,51.0,52.0,63.0,270.0
26,20194,CC,SB11201940516631,URBANO,N,A,TÉCNICO/ACADÉMICO,2.548740e+11,254874000363,54,...,Si,Si,Si,A1,52.0,46.0,41.0,43.0,55.0,233.0
28,20194,CC,SB11201940286383,URBANO,N,A,ACADÉMICO,3.544980e+11,354498002559,54,...,No,Si,Si,A-,47.0,49.0,47.0,45.0,52.0,241.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195829,20194,TI,SB11201940387027,URBANO,N,A,TÉCNICO/ACADÉMICO,1.548740e+11,154874000041,54,...,Si,Si,No,A-,28.0,42.0,33.0,45.0,37.0,192.0
195842,20194,TI,SB11201940338767,URBANO,N,A,ACADÉMICO,3.540010e+11,354001006530,54,...,Si,Si,Si,A2,64.0,58.0,47.0,62.0,63.0,290.0
195846,20194,TI,SB11201940481899,RURAL,N,A,TÉCNICO/ACADÉMICO,2.548100e+11,254810002061,54,...,No,No,Si,A-,36.0,61.0,61.0,56.0,65.0,294.0
195849,20194,TI,SB11201940350219,URBANO,N,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001001628,54,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195851,20194,TI,SB11201940550697,URBANO,N,A,ACADÉMICO,3.540010e+11,354001012211,54,...,No,Si,Si,A1,52.0,45.0,42.0,55.0,52.0,244.0