# Limpieza proyecto 3

#### Primero se trae la data del csv

In [1]:
import pandas as pd

data_completa = pd.read_csv("datos_norte_santander.csv")
data_completa.head()

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20112,TI,SB11201120186494,URBANO,N,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001009017,54,...,No,No,Si,A-,41.00,31.00,NaN,NaN,NaN,NaN
1,20194,TI,SB11201940250932,URBANO,NaN,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001002136,54,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
2,20194,TI,SB11201940250932,URBANO,NaN,A,TÉCNICO/ACADÉMICO,1.540010e+11,154001002136,54,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
3,20112,TI,SB11201120193635,RURAL,N,A,ACADÉMICO,2.540510e+11,254051000821,54,...,No,No,No,A-,34.00,39.00,NaN,NaN,NaN,NaN
4,20102,TI,SB11201020198930,URBANO,N,A,TÉCNICO/ACADÉMICO,1.548740e+11,154874000806,54,...,No,No,No,A-,38.53,50.82,NaN,NaN,NaN,NaN

#### Primero sacaremos algunas columnas que no nos van a aportar en nada

In [2]:
data = data_completa.drop(['estu_tipodocumento', 'estu_consecutivo', 'cole_cod_dane_establecimiento', 'cole_cod_dane_sede', 'cole_cod_depto_ubicacion', 
                  'cole_codigo_icfes', 'cole_depto_ubicacion', 'cole_nombre_establecimiento', 'cole_nombre_sede', 'cole_sede_principal', 
                  'estu_cod_depto_presentacion', 'estu_cod_reside_depto', 'estu_depto_presentacion', 'estu_depto_reside', 
                  'estu_estadoinvestigacion', 'estu_estudiante', 'estu_nacionalidad', 'estu_pais_reside', 'estu_privado_libertad'], axis=1)
data

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20112,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,TARDE,CÚCUTA,OFICIAL,...,No,No,Si,A-,41.00,31.00,NaN,NaN,NaN,NaN
1,20194,URBANO,NaN,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
2,20194,URBANO,NaN,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
3,20112,RURAL,N,A,ACADÉMICO,54051,MIXTO,COMPLETA,ARBOLEDAS,OFICIAL,...,No,No,No,A-,34.00,39.00,NaN,NaN,NaN,NaN
4,20102,URBANO,N,A,TÉCNICO/ACADÉMICO,54874,MIXTO,MAÑANA,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.53,50.82,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195852,20172,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,No,No,Si,A1,51.00,50.00,60.0,55.0,50.0,268.0
195853,20112,URBANO,N,A,TÉCNICO/ACADÉMICO,54518,MIXTO,COMPLETA,PAMPLONA,OFICIAL,...,No,No,Si,A2,56.00,85.00,NaN,NaN,NaN,NaN
195854,20142,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,...,No,No,No,A-,47.00,33.00,44.0,40.0,29.0,187.0
195855,20142,URBANO,N,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,...,No,No,No,A-,41.00,47.00,49.0,49.0,52.0,243.0
195856,20122,URBANO,N,A,ACADÉMICO,54001,MIXTO,COMPLETA,CÚCUTA,NO OFICIAL,...,Si,Si,Si,B1,77.00,97.00,NaN,NaN,NaN,NaN

#### Ahora revisamos los duplicados

In [3]:
duplicates = len(data[data.duplicated()])
print(f'Number of Duplicate Entries: {duplicates}')
data[data.duplicated()]

Number of Duplicate Entries: 35924

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
2,20194,URBANO,NaN,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,No,Si,Si,A-,32.0,45.0,42.0,42.0,49.0,218.0
6,20194,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
22,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,No,No,Si,A1,49.0,52.0,51.0,52.0,63.0,270.0
26,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,TARDE,LOS PATIOS,OFICIAL,...,Si,Si,Si,A1,52.0,46.0,41.0,43.0,55.0,233.0
28,20194,URBANO,N,A,ACADÉMICO,54498,MIXTO,NOCHE,OCAÑA,NO OFICIAL,...,No,Si,Si,A-,47.0,49.0,47.0,45.0,52.0,241.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195829,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54874,MIXTO,MAÑANA,VILLA DEL ROSARIO,OFICIAL,...,Si,Si,No,A-,28.0,42.0,33.0,45.0,37.0,192.0
195842,20194,URBANO,N,A,ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,NO OFICIAL,...,Si,Si,Si,A2,64.0,58.0,47.0,62.0,63.0,290.0
195846,20194,RURAL,N,A,TÉCNICO/ACADÉMICO,54810,FEMENINO,MAÑANA,TIBÚ,OFICIAL,...,No,No,Si,A-,36.0,61.0,61.0,56.0,65.0,294.0
195849,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195851,20194,URBANO,N,A,ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,NO OFICIAL,...,No,Si,Si,A1,52.0,45.0,42.0,55.0,52.0,244.0

#### Ahora quitamos los duplicados

In [4]:
data.drop_duplicates(inplace=True)
data

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20112,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,TARDE,CÚCUTA,OFICIAL,...,No,No,Si,A-,41.00,31.00,NaN,NaN,NaN,NaN
1,20194,URBANO,NaN,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,No,Si,Si,A-,32.00,45.00,42.0,42.0,49.0,218.0
3,20112,RURAL,N,A,ACADÉMICO,54051,MIXTO,COMPLETA,ARBOLEDAS,OFICIAL,...,No,No,No,A-,34.00,39.00,NaN,NaN,NaN,NaN
4,20102,URBANO,N,A,TÉCNICO/ACADÉMICO,54874,MIXTO,MAÑANA,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.53,50.82,NaN,NaN,NaN,NaN
5,20194,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.00,21.00,32.0,29.0,33.0,147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195852,20172,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,No,No,Si,A1,51.00,50.00,60.0,55.0,50.0,268.0
195853,20112,URBANO,N,A,TÉCNICO/ACADÉMICO,54518,MIXTO,COMPLETA,PAMPLONA,OFICIAL,...,No,No,Si,A2,56.00,85.00,NaN,NaN,NaN,NaN
195854,20142,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,...,No,No,No,A-,47.00,33.00,44.0,40.0,29.0,187.0
195855,20142,URBANO,N,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,...,No,No,No,A-,41.00,47.00,49.0,49.0,52.0,243.0
195856,20122,URBANO,N,A,ACADÉMICO,54001,MIXTO,COMPLETA,CÚCUTA,NO OFICIAL,...,Si,Si,Si,B1,77.00,97.00,NaN,NaN,NaN,NaN

#### Revisamos los valores nulos en la variable de salida puntajes globales "punt_global" y eliminamos las filas que tengan NaN o vacio

In [5]:
count_nan = data['punt_global'].isnull().sum()
count_nan

64830

In [6]:
data = data[data['punt_global'].notna()]
data

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
1,20194,URBANO,NaN,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,No,Si,Si,A-,32.0,45.0,42.0,42.0,49.0,218.0
5,20194,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
7,20172,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,Si,No,A-,43.0,28.0,33.0,36.0,37.0,171.0
8,20162,RURAL,N,A,TÉCNICO/ACADÉMICO,54810,MIXTO,MAÑANA,TIBU,OFICIAL,...,Si,Si,Si,A-,47.0,39.0,42.0,49.0,49.0,225.0
10,20172,URBANO,N,A,ACADÉMICO,54001,MIXTO,COMPLETA,CUCUTA,NO OFICIAL,...,Si,Si,Si,A-,47.0,44.0,41.0,44.0,54.0,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195848,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195850,20194,URBANO,N,A,ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,NO OFICIAL,...,No,Si,Si,A1,52.0,45.0,42.0,55.0,52.0,244.0
195852,20172,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,No,No,Si,A1,51.0,50.0,60.0,55.0,50.0,268.0
195854,20142,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,...,No,No,No,A-,47.0,33.0,44.0,40.0,29.0,187.0
195855,20142,URBANO,N,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,...,No,No,No,A-,41.0,47.0,49.0,49.0,52.0,243.0

#### Ahora revisamos el resto de las columnas, para revisar cual de estas tambien tiene valores en Nan o vacio

In [7]:
missing_values = data.isnull().sum()
missing_values

periodo                            0
cole_area_ubicacion                0
cole_bilingue                  13125
cole_calendario                    0
cole_caracter                   1606
cole_cod_mcpio_ubicacion           0
cole_genero                        0
cole_jornada                       0
cole_mcpio_ubicacion               0
cole_naturaleza                    0
estu_cod_mcpio_presentacion        0
estu_cod_reside_mcpio             67
estu_fechanacimiento               1
estu_genero                      133
estu_mcpio_presentacion            0
estu_mcpio_reside                 67
fami_cuartoshogar               1304
fami_educacionmadre             1857
fami_educacionpadre             1867
fami_estratovivienda            2076
fami_personashogar              1316
fami_tieneautomovil             1357
fami_tienecomputador            1303
fami_tieneinternet              1866
fami_tienelavadora              1286
desemp_ingles                      6
punt_ingles                        6
punt_matematicas                   0
punt_sociales_ciudadanas           0
punt_c_naturales                   0
punt_lectura_critica               0
punt_global                        0
dtype: int64

#### Nos damos cuenta que la columna "Cole_bilingue" tiene muchos null, asi que probamos cuantas filas se eliminarian si quitamos esta columna

In [8]:
df = data.drop('cole_bilingue', axis=1)
df = df.dropna()
df

,periodo,cole_area_ubicacion,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,estu_cod_mcpio_presentacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
1,20194,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,54001,...,No,Si,Si,A-,32.0,45.0,42.0,42.0,49.0,218.0
5,20194,URBANO,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,54874,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
7,20172,URBANO,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,54874,...,No,Si,No,A-,43.0,28.0,33.0,36.0,37.0,171.0
8,20162,RURAL,A,TÉCNICO/ACADÉMICO,54810,MIXTO,MAÑANA,TIBU,OFICIAL,54810,...,Si,Si,Si,A-,47.0,39.0,42.0,49.0,49.0,225.0
10,20172,URBANO,A,ACADÉMICO,54001,MIXTO,COMPLETA,CUCUTA,NO OFICIAL,54001,...,Si,Si,Si,A-,47.0,44.0,41.0,44.0,54.0,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195847,20172,URBANO,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,54405,...,Si,Si,Si,A2,65.0,61.0,57.0,58.0,59.0,296.0
195848,20194,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,54001,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195852,20172,URBANO,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,54405,...,No,No,Si,A1,51.0,50.0,60.0,55.0,50.0,268.0
195854,20142,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,54001,...,No,No,No,A-,47.0,33.0,44.0,40.0,29.0,187.0
195855,20142,URBANO,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,54498,...,No,No,No,A-,41.0,47.0,49.0,49.0,52.0,243.0

#### Tambien probamos si se dejaran todas las columnas, cuantas filas quedarian al quitar todos los null

In [9]:
data = data.dropna()
data

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
5,20194,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
7,20172,URBANO,N,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,...,No,Si,No,A-,43.0,28.0,33.0,36.0,37.0,171.0
8,20162,RURAL,N,A,TÉCNICO/ACADÉMICO,54810,MIXTO,MAÑANA,TIBU,OFICIAL,...,Si,Si,Si,A-,47.0,39.0,42.0,49.0,49.0,225.0
10,20172,URBANO,N,A,ACADÉMICO,54001,MIXTO,COMPLETA,CUCUTA,NO OFICIAL,...,Si,Si,Si,A-,47.0,44.0,41.0,44.0,54.0,229.0
17,20142,URBANO,N,A,TÉCNICO/ACADÉMICO,54003,MIXTO,TARDE,ABREGO,OFICIAL,...,No,No,Si,A-,47.0,44.0,41.0,31.0,36.0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195847,20172,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,Si,Si,Si,A2,65.0,61.0,57.0,58.0,59.0,296.0
195848,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195852,20172,URBANO,N,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,...,No,No,Si,A1,51.0,50.0,60.0,55.0,50.0,268.0
195854,20142,URBANO,N,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,...,No,No,No,A-,47.0,33.0,44.0,40.0,29.0,187.0
195855,20142,URBANO,N,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,...,No,No,No,A-,41.0,47.0,49.0,49.0,52.0,243.0

#### Escogemos el dataframe que tiene una columna menos ya que con este podemos tener 10000 datos mas

In [10]:
data = df
data

,periodo,cole_area_ubicacion,cole_calendario,cole_caracter,cole_cod_mcpio_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,estu_cod_mcpio_presentacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
1,20194,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,54001,...,No,Si,Si,A-,32.0,45.0,42.0,42.0,49.0,218.0
5,20194,URBANO,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,54874,...,No,No,No,A-,38.0,21.0,32.0,29.0,33.0,147.0
7,20172,URBANO,A,ACADÉMICO,54874,MIXTO,NOCHE,VILLA DEL ROSARIO,OFICIAL,54874,...,No,Si,No,A-,43.0,28.0,33.0,36.0,37.0,171.0
8,20162,RURAL,A,TÉCNICO/ACADÉMICO,54810,MIXTO,MAÑANA,TIBU,OFICIAL,54810,...,Si,Si,Si,A-,47.0,39.0,42.0,49.0,49.0,225.0
10,20172,URBANO,A,ACADÉMICO,54001,MIXTO,COMPLETA,CUCUTA,NO OFICIAL,54001,...,Si,Si,Si,A-,47.0,44.0,41.0,44.0,54.0,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195847,20172,URBANO,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,54405,...,Si,Si,Si,A2,65.0,61.0,57.0,58.0,59.0,296.0
195848,20194,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CÚCUTA,OFICIAL,54001,...,Si,Si,No,B+,83.0,79.0,81.0,72.0,71.0,382.0
195852,20172,URBANO,A,TÉCNICO/ACADÉMICO,54405,MIXTO,MAÑANA,LOS PATIOS,OFICIAL,54405,...,No,No,Si,A1,51.0,50.0,60.0,55.0,50.0,268.0
195854,20142,URBANO,A,TÉCNICO/ACADÉMICO,54001,MIXTO,MAÑANA,CUCUTA,OFICIAL,54001,...,No,No,No,A-,47.0,33.0,44.0,40.0,29.0,187.0
195855,20142,URBANO,A,TÉCNICO,54800,MIXTO,MAÑANA,TEORAMA,OFICIAL,54498,...,No,No,No,A-,41.0,47.0,49.0,49.0,52.0,243.0

#### Ahora  Revisamos que en nuestro dataframe ya no quede, ningun duplicado o null

In [11]:
duplicates = len(data[data.duplicated()])
print(f'Numero de duplicados: {duplicates}')
missing_values = data.isnull().sum().sum()
print(f'Numero de valores nullos: {missing_values}')

Numero de duplicados: 0
Numero de valores nullos: 0

#### Ahora revisamos cuales columnas nos quedan y cuales queremos sacar

In [12]:
data.dtypes

periodo                          int64
cole_area_ubicacion             object
cole_calendario                 object
cole_caracter                   object
cole_cod_mcpio_ubicacion         int64
cole_genero                     object
cole_jornada                    object
cole_mcpio_ubicacion            object
cole_naturaleza                 object
estu_cod_mcpio_presentacion      int64
estu_cod_reside_mcpio          float64
estu_fechanacimiento            object
estu_genero                     object
estu_mcpio_presentacion         object
estu_mcpio_reside               object
fami_cuartoshogar               object
fami_educacionmadre             object
fami_educacionpadre             object
fami_estratovivienda            object
fami_personashogar              object
fami_tieneautomovil             object
fami_tienecomputador            object
fami_tieneinternet              object
fami_tienelavadora              object
desemp_ingles                   object
punt_ingles                    float64
punt_matematicas               float64
punt_sociales_ciudadanas       float64
punt_c_naturales               float64
punt_lectura_critica           float64
punt_global                    float64
dtype: object